In [3]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt

In [7]:
import os

# Obtém o diretório atual
diretorio_atual = os.getcwd()
print(f"Diretório atual: {diretorio_atual}")

Diretório atual: \\wsl.localhost\Ubuntu-24.04\home\marcos\puc\Estatística\estatistica-aplicada-4T

In [ ]:
# Lendo o arquivo csv e passando para o pandas
df = pd.read_csv('./Dados/Anexo_Projeto_fifa_world_national_teams_versão_oficial_20241.csv', sep=';')

# Pegando as primeiras linhas do arquivo para verificar os dados
df.head()

,id,name,full_name,overall_rating,value_euro,wage_euro,nationality,national_team,club_team,age,...,crossing,finishing,heading_accuracy,short_passing,dribbling,jumping,strength,long_shots,aggression,GK_reflexes
0,158023,Messi,Lionel Andrés Messi Cuccittini,94,110500000,565000,Argentina,Argentina,FC Barcelona,31,...,86,95,70,92,97,68,66,94,48,8
1,153079,Aguero,Sergio Leonel Agüero del Castillo,89,64500000,300000,Argentina,Argentina,Manchester City,30,...,70,93,77,81,89,81,73,83,65,14
2,211110,Dybala,Paulo Bruno Exequiel Dybala,89,89000000,205000,Argentina,Argentina,Juventus,25,...,82,84,68,87,92,75,65,88,48,8
3,201399,Icardi,Mauro Emanuel Icardi Rivero,87,64500000,130000,Argentina,Argentina,Inter,26,...,46,91,91,73,77,94,76,70,56,9
4,226226,Lo Celso,Giovani Lo Celso,82,30000000,83000,Argentina,Argentina,Real Betis,22,...,75,77,59,82,84,64,69,76,65,14